### ISSUE TITLE
Add ability to list column dependents of answers/pinboards

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#11]
I have a use case to figure out what fields in a Worksheet are used by the user base. Getting a list of all the columns from each worksheet used in Answers/Pinboards will let me know if a column can be removed without severely affecting user experience. 

To accomplish this, I'd like to get a list from Dependency-Checker/ created-objects tools of all the columns used for all the pinboards answers in a system.

Tools 

- Dependency-Checker
- Created-objects

**Comment by boonhapus** [comment]
Added in [v1.2.0](https://github.com/thoughtspot/cs_tools/releases/tag/v1.2.0).
