### ISSUE TITLE
Missing '_updater.py', downloading from GitHub

### ISSUE THREAD

**Issue by chathawee** [thoughtspot/cs_tools#114]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

OS: Ubuntu
Python version: 3.10.12

### Description

Hi,
     I try to install the CS_tools and I got below error. Please suggest.

This is the error
    [PLATFORM DETAILS]
    Python Version: 3.10.12
       System Info: Linux (detail: Linux-5.15.0-100-generic-x86_64-with-glibc2.35)
     Platform Tags: linux-x86_64
            Ran at: 2024-03-26 16:03:16

INFO     | 2024-03-26 16:03:16,349 | <stdin>:395 | Missing '_updater.py', downloading from GitHub
INFO     | 2024-03-26 16:03:16,723 | <stdin>:400 | Downloaded as '_updater.py'
INFO     | 2024-03-26 16:03:16,738 | <stdin>:141 | Getting the latest CS Tools release.
INFO     | 2024-03-26 16:03:17,169 | <stdin>:143 | Found version: v1.4.16
INFO     | 2024-03-26 16:03:17,170 | <stdin>:146 | Installing CS Tools and its dependencies.
INFO     | 2024-03-26 16:03:17,185 | _updater.py:69 | /root/.config/cs_tools/.cs_tools/bin/python: No module named pip
DEBUG    | 2024-03-26 16:03:17,188 | <stdin>:519 | Error found: Failed with exit code: 1

**Comment by boonhapus** [comment]
@chathawee some operating system distributions do not come installed with python's `pip` by default. Can you try running this command?

`python -m ensurepip`

If it runs successfully, you should be able to re-run the initial CS Tools install command.

If it doesn't run successfully, we can try another way to get `pip` on that Linux machine.

**Comment by chathawee** [comment]
@boonhapus It didn't run successfully. How can I fix this? Thanks

**Comment by boonhapus** [comment]
@chathawee okay, let's try this instead. The first command will attempt to fetch the pip bootstrapper from python's source.

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

The second command runs the pip bootstrapper.

`python get-pip.py`

If these run successfully, then we should be able to run CS Tools's bootstrapper code from your initial command.

**Comment by chathawee** [comment]
Hi @boonhapus Still got the same error even I install pip successfully
root@ab-tscs-1001:~# pip --version
pip 24.0 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
root@sg-tscs-6001:~# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2574k  100 2574k    0     0  21.3M      0 --:--:-- --:--:-- --:--:-- 21.4M
root@ab-tscs-1001:~# python get-pip.py
Collecting pip
  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-24.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@ab-tscs-1001:~# pip --version
pip 24.0 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
root@ab-tscs-1001:~# curl --silent --show-error --location-trusted  https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py  | python3 - --install
14:54:06 | Welcome to the CS Tools Bootstrapper!
         | Ideally, you will only need to run this one time, and then your environment can be fully managed by CS Tools itself.
         | If you run into any issues, please reach out to us on GitHub Discussions below.
         |
         |           GitHub: https://github.com/thoughtspot/cs_tools/issues/new/choose
         |
         | Missing '_updater.py', downloading from GitHub
         | Downloaded as '_updater.py'
         | Getting the latest CS Tools release.
14:54:07 | Found version: v1.4.16
         | Installing CS Tools and its dependencies.
         | /root/.config/cs_tools/.cs_tools/bin/python: No module named pip

**Comment by chathawee** [comment]
@boonhapus I can solve it by removing the old cs_tool folder and reinstall it. Thank you.

**Comment by chathawee** [comment]
@boonhapus Now I got the error when trying to create the cluster config but I ran successfully on `cs_tools --version`
<img width="286" alt="Screenshot 2567-03-27 at 16 55 51" src="https://github.com/thoughtspot/cs_tools/assets/13635400/31f0be55-4215-441d-8cfa-8d5e411741e9">
<img width="1401" alt="Screenshot 2567-03-27 at 16 55 59" src="https://github.com/thoughtspot/cs_tools/assets/13635400/2ce0e05e-16b2-4c85-afda-4f43ff5cef7b">

**Comment by chathawee** [comment]
Hi @boonhapus I still got the same error. I have tried many scenarios
`--host ... --username ...`
`--host=... --username ...`
`--host ... --username=...`
`--config ... --host ... --username ...`
`--config=... --host ... --username ...`

This is the error that I got
<img width="1402" alt="Screenshot 2567-03-28 at 10 07 46" src="https://github.com/thoughtspot/cs_tools/assets/13635400/e747ea05-3b4d-48ec-ac5a-8921828e04ac">

**Comment by boonhapus** [comment]
Ah @chathawee , this looks like an issue due to **[typer's recent release](https://github.com/tiangolo/typer/releases/tag/0.10.0)**.

Please try to install the lower version for now.

`/root/.config/cs_tools/.cs_tools/bin/python --m pip install typer==0.9.0`

And then proceed with the config command again.

**Comment by chathawee** [comment]
Thanks @boonhapus. After downgrade the typer. I have to remove the cs_tools folder again.
Now I can run on the `config create`  command but when I try to run `config check`. I faced the error about the 403. However, I have tested the same config on another OS (Mac) and it return the Login success! but on this Ubuntu, it return 403 error code instead (Please see the attached image)

Run on Mac
<img width="358" alt="Screenshot 2567-03-28 at 10 49 43" src="https://github.com/thoughtspot/cs_tools/assets/13635400/96ff4d6a-5878-4ce9-b5fc-7b18c3142cc5">

Run on Ubuntu
<img width="1408" alt="Screenshot 2567-03-28 at 10 45 17" src="https://github.com/thoughtspot/cs_tools/assets/13635400/f2996038-8637-44de-9457-f5f68dbc7d86">
<img width="1114" alt="Screenshot 2567-03-28 at 10 45 27" src="https://github.com/thoughtspot/cs_tools/assets/13635400/4ac69599-bc17-4f90-8045-e703b57049bb">

Do you have any suggestion?

**Comment by boonhapus** [comment]
I'm sorry that this is so difficult @chathawee 😢 It looks like maybe your Ubuntu server is behind a proxy or network gate of some sort? Are you able to ping the server directly ?

`curl -Iks <url of your ts cluster>`  ( this is an uppercase `i` )

**Comment by chathawee** [comment]
@boonhapus Thank you. I can access the cluster now. This is related to the network. So I have changed to use the URL instead of the IP address. It works fine. Thanks a lot.
