### ISSUE TITLE
tmlfs cleanup error as it detects directory is not tmlfs root

### ISSUE THREAD

**Issue by felipemm** [thoughtspot/cs_tools#136]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

```
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                      │
│           Info snapshot taken on 2024-05-14                                                                          │
│                                                                                                                      │
│               CS Tools: 1.5.5                                                                                        │
│         Python Version: Python 3.9.16 (main, Jan  4 2023, 11:12:52)                                                  │
│    [Clang 14.0.0 (clang-1400.0.29.202)]                                                                              │
│            System Info: Darwin (detail: macOS-12.7.5-x86_64-i386-64bit)                                              │
│      Configs Directory: /Users/ {anonymous} /Library/Application Support/cs_tools                                    │
│    Activate VirtualEnv: source "/Users/ {anonymous} /Library/Application Support/cs_tools/.cs_tools/bin/activate"    │
│          Platform Tags: macosx-12.6-x86_64                                                                           │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```

### Description

Tried to cleanup my current tmlfs, got error that directory is not root of tmlfs, but it is.

Also, raised error is regarding CSToolsError class not taking arguments, which seems a bug on this class or how it is manipulated.

![image](https://github.com/thoughtspot/cs_tools/assets/2068687/3817dc58-9ae4-4e11-8958-8a1b877fd3e4)

**Comment by billdback-ts** [comment]
@felipemm I'm adding a fix today, but you can get past this by creating a file called ".tmlfs" in the root directory.  It's supposed to be created on initial FS creation, but wasn't.

**Comment by boonhapus** [comment]
@felipemm if you upgrade to 1.5.6 , this should be resolved.

```
curl -sSL https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python3 - --install
```

**Comment by felipemm** [comment]
just to make sure: this cleanup only remove logs, not TMLs?

It seems it is not working:
<img width="1135" alt="image" src="https://github.com/thoughtspot/cs_tools/assets/2068687/de51ffe3-b087-4acd-a67a-13ef7f332770">

**Comment by billdback-ts** [comment]
Yes, it only removes old logs, not TML files.  Is that list of TML files in the logs folder?  Looks like you are printing the liveboard folder.

**Comment by boonhapus** [comment]
Closing as the underlying issue seems to be resolved. Feel free to re-open if there are still issues!
