### ISSUE TITLE
Importing an exported "system liveboard" such as "Object Usage" breaks the liveboard 

### ISSUE THREAD

**Issue by felipemm** [thoughtspot/cs_tools#137]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

![image](https://github.com/thoughtspot/cs_tools/assets/2068687/a2ead30c-ca21-41d9-86de-4cb2ce6bb44f)

### Description

importing the liveboard exported from a different cluster breaks the liveboard beyound repair. Can we filter the "system" liveboards from the export?

![image](https://github.com/thoughtspot/cs_tools/assets/2068687/291c2089-130a-457c-aa75-8553ba12b103)

![image](https://github.com/thoughtspot/cs_tools/assets/2068687/06f90e38-8eb0-4489-bf21-8f4c72b96374)

**Comment by boonhapus** [comment]
This one is interesting, I actually had no idea we could export system objects like this. I agree that we should be excluding system-user content. Good catch on this, will add it as a restriction.

**Comment by boonhapus** [comment]
@felipemm if you upgrade to 1.5.6 , this should be resolved.

```
curl -sSL https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python3 - --install
```

**Comment by boonhapus** [comment]
@felipemm did this resolve your issue?

**Comment by felipemm** [comment]
Hi @boonhapus, sorry for the late response. I did see that no system liveboard was exported, but I saw that cs_tools tries to export system worksheets such as TS: BI Server. Maybe we can filter it out?

![image](https://github.com/thoughtspot/cs_tools/assets/2068687/bb94fcb6-5bbd-40d1-875f-59a12d449047)

**Comment by boonhapus** [comment]
When using the new default setting of `--no-include-system-content` , I no longer see any system-owned content being exported. If you're not finding the same, please re-open this issue so we can look into it.
