### ISSUE TITLE
exporting connections along with liveboards and worksheets does not work

### ISSUE THREAD

**Issue by felipemm** [thoughtspot/cs_tools#146]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

<img width="1084" alt="image" src="https://github.com/thoughtspot/cs_tools/assets/2068687/3e0e628b-800a-44ce-99ca-3a89e58e8cbf">

### Description

When running the following command:
`cs_tools tools scriptability export --include-types answer,connection,liveboard,table,sqlview,view,worksheet --export-associated --org 789183452 . --config prod`

It is expected to export all objects, including connections, however connection folder is empty and there is no connection entry on export results.

**Comment by boonhapus** [comment]
This is likely due to #145 as well.

**Comment by boonhapus** [comment]
I'm actually able to reproduce this without the connection itself failing to export (via API) ... it just appears it doesn't get processed or saved for some reason. 😓 Will look into fixing this one. For now, the export will have to be split into 2 steps -- one with connection only, and one with all other content.

**Comment by billdback-ts** [comment]
@felipemm Just a head's up that this issue has been discovered.  The solution is in review, but hopefully we'll have an updated version soon.
