### ISSUE TITLE
 Object of type datetime is not JSON serializable in gather

### ISSUE THREAD

**Issue by kaypro4** [thoughtspot/cs_tools#156]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

![cs-tools-info-2024-07-12](https://github.com/user-attachments/assets/90fd2ecf-467f-470f-a943-bfca2a438b2a)

### Description

Hello, when I execute this commend:

`cs_tools tools searchable gather --syncer json://directory=.`

I receive this error "TypeError: Object of type datetime is not JSON serializable"

I am able to execute this command `cs_tools tools searchable gather --syncer csv://directory=.` successfully. When I run the json version it generates ts_org.json and ts_cluster.json and then throws the error.

Thanks!
Matt

**Comment by boonhapus** [comment]
Thanks for reporting this @kaypro4 ! I'll release a fix within a few days, should be easy enough.

**Comment by boonhapus** [comment]
This should be fixed in **[v1.5.9](https://github.com/thoughtspot/cs_tools/releases/tag/v1.5.9)** , feel free to re-open if this still doesn't work.
