### ISSUE TITLE
Getting an error while installing the CS tool on windows environment

### ISSUE THREAD

**Issue by SSangoju** [thoughtspot/cs_tools#159]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

https://thoughtspot.github.io/cs_tools/

### Description

while installing the CS tool we are getting the below error, 

"
PS C:\Users\Santhosh_Sangoju> powershell -c "IRM https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | py - --install"
IRM :
McAfee Web Gateway - Notification - Authentication Required
Authentication Required

      You must be authenticated to access this URL.

   urlprotocol = "https";
   statuscode=407;
   if(statuscode==401 && urlprotocol == "ftp"){
      document.write("");
      document.write("");
      document.write("Please enter your credentials in the form below and click \"Access FTP\" button if your browser
doesn't present authentication prompt for FTP sites.");
      document.write("Username:");
      document.write("Password:");
      document.write("");
      document.write("");
      document.write("");
   }

   function redirectToFTP(){
      var username=unescape(document.getElementById("ftpUsername").value);
      var password=unescape(document.getElementById("ftpPassword").value);
      location.href = "ftp://"+username+":"+password+"@raw.githubusercontent.com:443"
   }

      URL: break_line("https://raw.githubusercontent.com");

Proxy: usps3mwgproxy01Rule: Perform Authentication

Internet Usage Policy

Internet Usage Policy applies to all employees of Dell Inc. who have access to computers and the Internet to be used
in the performance of their work. Use of the Internet by employees of Dell Inc. is permitted and encouraged where such
use supports the goals and objectives of the business. However, access to the Internet through Dell Inc. is a
privilege and all employees must adhere to the policies concerning Computer, Email and Internet usage. Violation of
these policies could result in disciplinary and/or legal action leading up to and including termination of employment.
Employees may also be held personally liable for damages caused by any violations of this policy. All employees are
required to acknowledge receipt and confirm that they have understood and agree to abide by the rules hereunder on a
periodic basis.

At line:1 char:1
+ IRM https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand"  

It would appreciate it if somone could help on this error.

Regards,
Santhosh.

**Comment by boonhapus** [comment]
> Proxy: usps3mwgproxy01Rule: Perform Authentication
> Internet Usage Policy

@SSangoju it appears that your organization does not allow you to install python utility unless they bypass the proxy or hit an internal FTP.

I can build an offline binary for you (no outside internet access necessary) if that would help. Can you share the output of this command?

`python -m sysconfig | select -first 20`

**Comment by SSangoju** [comment]
Hi,

Thanks for your response.

I ran suggested command, and the result is below:

“
PS C:\WINDOWS\system32> python -m sysconfig | select -first 20
Platform: "win-amd64"
Python version: "3.12"
Current installation scheme: "nt"

Paths:
        data = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312"
        include = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Include"
        platinclude = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Include"
        platlib = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Lib\site-packages"
        platstdlib = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Lib"
        purelib = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Lib\site-packages"
        scripts = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Scripts"
        stdlib = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Lib"

Variables:
        BINDIR = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312"
        BINLIBDEST = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Lib"
        EXE = ".exe"
        EXT_SUFFIX = ".cp312-win_amd64.pyd"
        INCLUDEPY = "C:\Users\Santhosh_Sangoju\AppData\Local\Programs\Python\Python312\Include"
PS C:\WINDOWS\system32> “




Regards,
Santhosh.




Internal Use - Confidential

**Comment by boonhapus** [comment]
@SSangoju , please try **[this link](https://thoughtspot.egnyte.com/dl/0bO8XlNKGF)**

> To install the offline binary, we need to run these two steps.
> - Extract the zip file.
> - Run python against the _bootstrapper.py file with --offline-mode specified
> 
> cd cs-tools_1.5.9b4_linux-x86_64_3.12
> python _bootstrapper.py --install --no-clean --offline-mode .

**Comment by boonhapus** [comment]
Closing this as it's been some time since we last heard from you. Feel free to reopen the issue or create a new one if you're still having problems!
