### ISSUE TITLE
Issue with Archiver Remove

### ISSUE THREAD

**Issue by robertholmes3** [thoughtspot/cs_tools#168]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│           Info snapshot taken on 2024-09-01                                  │
│                                                                              │
│               CS Tools: 1.5.9                                                │
│         Python Version: Python 3.10.14 (main, Jul 10 2024, 09:56:15)         │
│    [Clang 15.0.0 (clang-1500.3.9.4)]                                         │
│            System Info: Darwin (detail: macOS-14.5-arm64-arm-64bit)          │
│      Configs Directory: /Users/ {anonymous} /Library/Application             │
│    Support/cs_tools                                                          │
│    Activate VirtualEnv: source "/Users/ {anonymous} /Library/Application     │
│    Support/cs_tools/.cs_tools/bin/activate"                                  │
│     System Python Path: /Users/ {anonymous} /Library/Application             │
│    Support/cs_tools/.cs_tools/bin/python                                     │
│          Platform Tags: macosx-14.5-arm64                                    │
│

### Description

I am able to run all other tools but when I try remove we get the error:

AttributeError: 'RESTAPIv1' object has no attribute 'post'

**Comment by boonhapus** [comment]
@robertholmes3 can you update to `1.5.10b3` ? I should have just fixed this one.

```shell
curl \
    --silent --show-error --location-trusted \
    https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py \
    | python3 - --install --beta
```

**Comment by robertholmes3** [comment]
Thank @boonhapus, this worked! Just FYI the --export-only does not seem to work

**Comment by boonhapus** [comment]
What do you mean by it doesn't work @robertholmes3 ? 🤔 When provided, this should skip the `delete content` and `delete tag` steps.

**Comment by robertholmes3** [comment]
apologies - for me it didn't export any tml @boonhapus

**Comment by robertholmes3** [comment]
ah i missed --directory ! @boonhapus

**Comment by boonhapus** [comment]
I can add some cli validation to whine if you supply `--export-only` without `--directory` , that's a better UX than a seemingly silent failure. Thanks!

**Comment by boonhapus** [comment]
Will close this one now, the fix provided in the beta will fold into the latest public release as well. Feel free to reopen the issue if you run into any other bugs!
