### ISSUE TITLE
CSS Tools Install Issue

### ISSUE THREAD

**Issue by OYTUNTUNCEL** [thoughtspot/cs_tools#169]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

cs_tools : The term 'cs_tools' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cs_tools self info --anonymous --directory
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cs_tools:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### Description

To whom it may concern,

I am reaching out for assistance with configuring the CSS Tools for our customer. This is my second attempt. During my first attempt, I successfully reached the "Using Syncers" step but encountered an error that prevented me from proceeding further. Unfortunately, my computer was reset, and I now have to start the process from the beginning.

I followed the instructions in the documentation and downloaded Python as required. However, this time, I encountered an issue right at the first step when trying to run the following code:

powershell -c "IRM https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python - --install"

I have attached the log file for your reference. Any assistance you can provide would be greatly appreciated, as our client is eager to start using the CSS Tools features as soon as possible.

[cs_tools-bootstrap-error-tmp_xkqpxp6.log](https://github.com/user-attachments/files/16850629/cs_tools-bootstrap-error-tmp_xkqpxp6.log)

Thank you in advance for your help.

Best regards,
Oytun

**Comment by boonhapus** [comment]
@OYTUNTUNCEL can you try running the powershell command with `--reinstall` as opposed to `--install` ?

```shell
powershell -c "IRM https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python - --reinstall"
```

**Comment by OYTUNTUNCEL** [comment]
Thanks for your response @boonhapus ,

I just run the code and faced an issue. I have attached the new log for your reference. 

[cs_tools-bootstrap-error-tmpd_qvvvk5.log](https://github.com/user-attachments/files/16850960/cs_tools-bootstrap-error-tmpd_qvvvk5.log)

**Comment by boonhapus** [comment]
Hey @OYTUNTUNCEL ok let's try one last escape hatch... can you open powershell and follow these steps? We're going to remove the existing cs tools environment and then try installing again.

- run the powershell command `explorer $env:APPDATA\cs_tools`
- delete the `.cs_tools` directory as a whole (notice the leading period `.`)
- run the cs_tools install command again

```shell
powershell -c "IRM https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python - --reinstall --verbose"
```

If this doesn't work, we may need to get on a call together to resolve the issue. Python environments in Windows can sometimes get tricky.

**Comment by OYTUNTUNCEL** [comment]
Thanks for your reply @boonhapus. 

Unfortunately, it didn’t work. I have attached the most recent log file for your reference.

[cs_tools-bootstrap-error-tmpf9j3xoad.log](https://github.com/user-attachments/files/16852674/cs_tools-bootstrap-error-tmpf9j3xoad.log)

It would be great if we could hop on a call to resolve the issue. If you could share your email and available times, I can send you a meeting invitation. Thanks again!

**Comment by boonhapus** [comment]
@OYTUNTUNCEL shoot me an email and let's find a time there, likely later this week. I am in US/Central timezone.

nicholas.cooper@thoughtspot.com

**Comment by boonhapus** [comment]
We met directly to resolve this issue. 👍
