### ISSUE TITLE
Ability to List Objects users have access to (Pinboards, Worksheets, Answers)

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#17]
Customer audit team would like to see which groups can access which worksheets. Should show access to object and context (direct share, which group)

Customers:
Canadian Tire
Verisk
Mattel

Requester: Jake Parker, Devin, Jeff Dean

**Comment by boonhapus** [comment]
📌 Implemented in [v1.3.0](https://github.com/thoughtspot/cs_tools/releases/tag/v1.3.0).
