### ISSUE TITLE
AttributeError: 'formatConfigDetails' is set to 'currencyFormatConfig', not 'numberFormatConfig'

### ISSUE THREAD

**Issue by jmmizerany** [thoughtspot/cs_tools#170]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

![cs-tools-info-2024-09-12](https://github.com/user-attachments/assets/272abcc4-5aff-4456-ad30-3947107c74b4)

### Description

When performing a `cs_tools tools scriptability export` on our cluster, when it gets to exporting liveboards this is where issues arise. I was able to modify the source code and grab the outputs where it's failing

```

FormatConfig(category='CURRENCY', numberFormatConfig=None, percentageFormatConfig=None, currencyFormatConfig={'locale': 'USD', 'unit': 'AUTO', 'decimals': 2.0, 
'toSeparateThousands': True}, customFormatConfig=None, isCategoryEditable=True) category
FormatConfig(category='CURRENCY', numberFormatConfig=None, percentageFormatConfig=None, currencyFormatConfig={'locale': 'USD', 'unit': 'AUTO', 'decimals': 2.0, 
'toSeparateThousands': True}, customFormatConfig=None, isCategoryEditable=True) numberFormatConfig
```

**Comment by boonhapus** [comment]
@jmmizerany This looks like it could be related to **[thoughtspot_tml#24](https://github.com/thoughtspot/thoughtspot_tml/issues/24)** , I'll restrict `cs_tools` to `betterproto[compile] < 2.0.0b7` and deploy over the the weekend.

On Monday, please update to 1.5.10 and try your `scriptability export` again.

```shell
curl \
    --silent --show-error --location-trusted \
    https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py \
    | python3 - --install
```

**Comment by jmmizerany** [comment]
> @jmmizerany This looks like it could be related to **[thoughtspot_tml#24](https://github.com/thoughtspot/thoughtspot_tml/issues/24)** , I'll restrict `cs_tools` to `betterproto[compile] < 2.0.0b7` and deploy over the the weekend.
> 
> On Monday, please update to 1.5.10 and try your `scriptability export` again.
> 
> ```shell
> curl \
>     --silent --show-error --location-trusted \
>     https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py \
>     | python3 - --install
> ```

Great thank you! Also, is this project available for the community to contribute to? If so I don't mind opening a PR to fix this too

**Comment by boonhapus** [comment]
@jmmizerany it totally is open to the community.. but I also recognize that it's a medium large code base and a 5yr project with plenty of tech debt 😅

This change should be trivial, it's just adding the restriction to `pyproject.toml` (right now `betterproto` is transitive via `thoughtspot_tml`... and will likely go back to transitive once I get some time to fix #24).

**Comment by boonhapus** [comment]
`pip`'s a little bit too eager to skip recent betas apparently. We got there with something more explicit though `betterproto[compiler] >= 2.0.0b5 , < 2.0.0b7` 

Try updating to the latest CS Tools and LMK if that resolves your error @jmmizerany

**Comment by jmmizerany** [comment]
> `pip`'s a little bit too eager to skip recent betas apparently. We got there with something more explicit though `betterproto[compiler] >= 2.0.0b5 , < 2.0.0b7`
> 
> Try updating to the latest CS Tools and LMK if that resolves your error @jmmizerany

Just verified this works! Thank you! 🚀
