### ISSUE TITLE
v1.3.0 planning - Go-Live on TS Community?

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#19]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

We should look to publish the CS Tools project on ThoughtSpot Community. Below is a task list of items to complete prior to landing.

**TS Community Post**
- [x] Install, Config & Admin - messaging around how to make your life easier as an administrator
- [x] Developers - messaging around "this a complex project built on top of rest apis"

**KB Articles**
- [x] How-to Implement: Archiver
- [ ] How-to Implement: Searchable Dependencies
- [ ] How-to Implement: Falcon Sharding Recommender
- [x] How-to Implement: TS: BI Extractor
- [x] Linkback to KB Articles with the #cstools tag

**New Tool: User Management**
- [x] #13 
    aka [sync users](https://github.com/thoughtspot/user_tools/blob/master/user_tools/sync_from_excel.py)
- [x] **New Tool: Get Permissions** - implement `get_user_permissions.py`
- [ ]  **New Tool: Mass Tagging to enable other tools**

**Documentation**
- [x] Make all but Falcon Sharding Recommender public
- [x] Windows .bat script and install process

**Bugfix**
- [x] #18 
- [x] interactive config mode is broken for some required arguments
- [x] create parent directory(s) on `--export` if they do not exist
- [x] current SpotApps were built against 7.0.x, need valid back to 6.3.x versions
- [x] `http_timeout` on remote tql and dataload services needs to be configurable
- [x] bump dependencies for py310 support

**FR**
- [ ] Add a way for `--config` to come after cs_tools
  `cs_tools --config tools ...` vs `cs_tools tools ... --config`

**Comment by boonhapus** [comment]
It would be great to have KB articles that point to implementations, or use cases that were derived from implemented these tools. Basically a "how-to" guide that we can link out to!

**Comment by boonhapus** [comment]
Updated the OP to include all things we need for TS Community rollout, this is off the top of my head right now.

**Comment by boonhapus** [comment]
we should do this too

[user permissions.zip](https://github.com/thoughtspot/cs_tools/files/8233713/user.permissions.zip)

**Comment by boonhapus** [comment]
📌 Implemented in [v1.3.0](https://github.com/thoughtspot/cs_tools/releases/tag/v1.3.0).
