### ISSUE TITLE
You can delete content where the GUID and type don't match

### ISSUE THREAD

**Issue by billdback-ts** [thoughtspot/cs_tools#20]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

cstools tools bulk-deleter single --config training --type "pinboard" --guid "8ba1de1c-aa35-45f0-9282-c9c630a7f775"
deleting object .. PINBOARD_ANSWER_BOOK ... 8ba1de1c-aa35-45f0-9282-c9c630a7f775 ... 

MacOS Monterey
MacBook Pro

### Example Command

cstools tools bulk-deleter single --config training --type "pinboard" --guid "8ba1de1c-aa35-45f0-9282-c9c630a7f775"

### Description

I gave the wrong GUID, which is one that referenced a System Table.  It deleted the table, even though the type specified was pinboard.

**Comment by boonhapus** [comment]
https://github.com/thoughtspot/cs_tools/blob/7b516476be94adf7f121645b7c3fc7206fdae4ca/cs_tools/tools/_bulk-deleter/app.py#L129-L130

We'll report this one internally as well, as I don't believe this is intended behavior. In the meantime, I'll add a check against system content at the very least.

**Comment by boonhapus** [comment]
🛡 Added a guard in [v1.3.0](https://github.com/thoughtspot/cs_tools/releases/tag/v1.3.0).
