### ISSUE TITLE
Allow searchable gather to extract/update a specific table

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#27]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Searchable can take a while with large server instances since it populates the full searchable schema. I would like to update a specific table (as opposed to the whole model) if I want to.

**Comment by boonhapus** [comment]
We should also look into gracefully failing + logging during the data extraction & processing steps for this command.
