### ISSUE TITLE
Include full syncer details in config

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#28]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

I have struggled to teach new people about how to configure syncers. The current setup is very flexible, but not user friendly for people new to the tools. I've got two suggestions to help people get up and running faster:
1: Allow syncer text to be written/read from config files
2: include default properties for .csv and falcon, so you don't actually need to have syncers for those at all

**Comment by boonhapus** [comment]
I see this as two* separate issues.

- Documentation needs to be clearer on Syncer configuration and usage.
- Getting started is difficult.

For the first issue, what can we do to make the syncer docs more clear from a user perspective?

For the second, I'm going to be removing the how-to pages for a single tutorial-style guide which will directly walk through the steps of download + install, setting up a configuration file, defining a syncer toml, and then using all of that to run a single command.

* I'm not convinced about putting syncer configuration directly into the main configuration itself. The pass-thru of details can be handled when we issue `cs_tools config show --config prod`.

**Comment by boonhapus** [comment]
This is resolved as part of V1.4.0

![img](https://raw.githubusercontent.com/thoughtspot/cs_tools/gh-pages/terminal-screenshots/cs_tools_config_show___config_non_prod___anonymous.svg)
