### ISSUE TITLE
Change ownership of objects moved via TML

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#31]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Summary
When creating objects via TML, the owner is set to the user that imports the the TML. In a migration use case, you want the owners to be the same in the target and the source.

### Implementation Thoughts:

- I think this makes the most sense to live in scriptability as an option on the import step (default off). The usability would be reduced if you have to tell the tools to include owners on export, we should just take a manifest of that no matter what. This would also allow someone to "tweak" owners manually before importing if they want to.
- The "owner" should be based on username as opposed to guids since the source and target clusters have different user guids.
- Code should have error handling to survive if the transfer to user does not exist and keep going (as opposed to failing all together).

**Comment by boonhapus** [comment]
At the moment, I would recommend doing this as part of a second command. We can use `user-management transfer-ownership`.

![img](https://github.com/thoughtspot/cs_tools/blob/gh-pages/terminal-screenshots/cs_tools_tools_user_management_transfer___help.svg)
