### ISSUE TITLE
Create ability to extract and apply sharing settings of objects (worksheets, answers, etc)

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#32]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

One issue with migrating content from one instance to another (like on prem to cloud) is that standard TML does not include sharing settings. This is one of the main issues with a TML migration vs metadata. 

This could also provide a way to mass apply sharing settings on objects in more mature environments. 

#### Implementation Notes:

- This may make sense to be a feature in Scriptability, but it should also be stand alone function in **user tools**, like transfer_owner
- Format of the sharing settings export should mirror what comes out of **Searchable** if possible.

**Comment by DevinMcPherson-TS** [comment]
Found another use case for this tool. When users or admins want to share one or more objects with a large list of people (as opposed to using groups). In larger companies, it is impractical to have an AD group or TS group for every set of people that might need access to a Liveboard/Answer.

**Comment by boonhapus** [comment]
This capability exists as part of Scriptability.
