### ISSUE TITLE
Publish cs_tools to Pypi

### ISSUE THREAD

**Issue by afranzi** [thoughtspot/cs_tools#33]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Hi there!

I was wondering if you could publish the library to Pypi so it's easy to integrate it with our processes instead of being force to interact with the ZIP files.

Thank you! 💌

**Comment by boonhapus** [comment]
Hi @afranzi , this is something our team has given thought to a few times.

In the near future, we plan to have a remote-install option in the bootstrapper. This will allow users to check, fetch, and install the latest version all without having to download the heavy zip files.

What would your process look like if the library were on PyPI ?

- SN

**Comment by afranzi** [comment]
> What would your process look like if the library were on PyPI ?

- We could integrate it directly into our Python code without requiring us to use the ZIP command line.

**Comment by boonhapus** [comment]
We're not currently set up for this to work flawlessly, but would something like this work for you?

`pip install git+https://github.com/thoughtspot/cs_tools.git@v1.3.3`

**Comment by boonhapus** [comment]
This is resolved as part of V1.4.0 . Check the release notes to learn more.

https://thoughtspot.github.io/cs_tools/changelog/1.4.0
