### ISSUE TITLE
Add ability to transfer ownership of Dataflow jobs

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#34]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

There is a separate transfer ownership API for dataflow introduced in 7.2sw. I'd like an additional function in User Management to allow transferring ownership of dataflow jobs. If we want to get fancy, we'll just check the object based on guid and call the right endpoint as opposed to having two different end user functions .
Syntax:

curl -X GET "<protocol>://<instance>/dataflow/diapi/transferofownership?fromUserName=<from user login Id>&toUserName=<to user login Id>" -b 'JSESSIONID=<jsessionid>' <insecure>

**Comment by boonhapus** [comment]
This is resolved as part of V1.4.0 . Check the release notes to learn more.

https://thoughtspot.github.io/cs_tools/changelog/1.4.0

![img](https://raw.githubusercontent.com/thoughtspot/cs_tools/gh-pages/terminal-screenshots/cs_tools_tools_user_management_transfer___help.svg)
