### ISSUE TITLE
Add config location to the `cstools config --help`

### ISSUE THREAD

**Issue by billdback-ts** [thoughtspot/cs_tools#35]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

You can see the configuration location using `cstools config show`, but I'd also like to see the location in the `cstools config --help`.  I want this for two reasons.  First, I sometimes just want the location.  Second, if I can't remember the full command, I type `--help` to get the command already, so it saves a step.

**Comment by boonhapus** [comment]
This is resolved as part of V1.4.0 . Check the release notes to learn more.

https://thoughtspot.github.io/cs_tools/changelog/1.4.0

![img](https://raw.githubusercontent.com/thoughtspot/cs_tools/gh-pages/terminal-screenshots/cs_tools_config_show___config_non_prod___anonymous.svg)
