### ISSUE TITLE
CSV Syncer Error in Windows

### ISSUE THREAD

**Issue by aldrichsison-cwt** [thoughtspot/cs_tools#37]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Hi! I'm trying to test out the CSV Syncer in Windows.
However, I'm stuck with an error when I try to run the following command:
`cs_tools config modify --config prod --syncer csv://$env:USERPROFILE\Downloads\report.toml`

The error is:
```
Your csv syncer encountered an error.                                                                                                                                    main.py:209
           Couldn't read the Syncer definition at C:\Users\aldri\Downloads\report.toml
```

I already tried escaping backslashes in filepaths and flipping them, to no success.

**Comment by boonhapus** [comment]
Hi @aldrichsison-cwt , can I assume you were following [our tutorial](https://thoughtspot.github.io/cs_tools/tutorial/syncer/#set-up-the-csv-syncer) and ran into this issue?

Can you share the contents of your CSV syncer? Windows is always fun about slashes..

**Comment by aldrichsison-cwt** [comment]
Hi @boonhapus, yes, I was following the tutorial.

I just have this for CSV Syncer:
```
[configuration]
directory = "C:\\Users\\aldri\\Downloads\\"
```

then also tried:
```
[configuration]
directory = "C:/Users/aldri/Downloads/"
```

**Comment by boonhapus** [comment]
Did you save that file to `C:\Users\aldri\Downloads` ? I'm unable to reproduce the issue by running through the tutorial.

**Comment by aldrichsison-cwt** [comment]
Hi @boonhapus ,
Yes, the .toml file is saved in that directory.
May I know if you're using Windows Terminal or PowerShell? And which version?

**Comment by aldrichsison-cwt** [comment]
And may I see sample setting of CSV Syncer inside a config file when it's set to default?

**Comment by boonhapus** [comment]
And finally, Windows Terminal with the Powershell profile, though it's slightly customized as you can tell. It's all pretty stuff though, shouldn't impact tokenization and parsing of CLI args.

![image](https://user-images.githubusercontent.com/14192437/189713521-3dda73a7-797c-4e7d-a856-a0d1b2be89cc.png)

**Comment by aldrichsison-cwt** [comment]
Hi @boonhapus.
Finally got it working.
I did the following:
- Installed PowerShell 7.2; I was previously using version 5.1
- I replicated the path and definition file you sent

I'm guessing there is something like a permission setting with the previous path or file I used; probably why the program can't access or read the definition file.

Thank you so much for responding. Cheers!
