### ISSUE TITLE
Install CS tools

### ISSUE THREAD

**Issue by elisamorariu** [thoughtspot/cs_tools#40]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

I am trying to install CS tools.
I get to the point where I get this message:
"You've got one of those fancy new Apple M1 chips! Unfortunately, CS Tools doesn't yet support offline installs for this chipset yet. For the time being, you'll have to follow these manual instructions first."
The first step is:
 "# Change directory to the CS Tools internal application directory.
     |  cd "$HOME/Library/Application Support/cs_tools"  "
I am able to navigate to the Library/Application Support, but it does not have the cs_tools directory, although I have downloaded the package. 
Is there any other place I can download it from or is there anything that I am not doing to get there?

Thank you!

**Comment by boonhapus** [comment]
I met with Elisa and follow [these instructions](https://github.com/thoughtspot/cs_tools/issues/29#issuecomment-1179370072).

After following those instructions, we needed to comment out L66-68 in `_activator.py` to properly set up the shell profile. This should get fixed as part of #39.

https://github.com/thoughtspot/cs_tools/blob/39f776848ab0d515f48709ba29b9d624beac5293/dist/bootstrap/_activator.py#L66-L68
