### ISSUE TITLE
Write multiple clusters data to the same tables with Searchable

### ISSUE THREAD

**Issue by DevinMcPherson-TS** [thoughtspot/cs_tools#43]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

I would like to be able to combine Searchable Output data from multiple clusters. 

Why?
I may have multiple prod cloud or on prem clusters and want to report on all usage. I also could be in the process of a sw to cloud migration and want to see usage move from on prem to cloud.

Implementation notes:
The easiest way to do this would be to add a "cluster" column to the existing table structures. User can input that value in the command line as a separate value, but I suggest using the server URL from the connection.

**Comment by boonhapus** [comment]
This is implemented as part of 1.5.0.
