### ISSUE TITLE
Bulk update for display names using user-management

### ISSUE THREAD

**Issue by aldrichsison** [thoughtspot/cs_tools#44]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Hello!

Other than renaming usernames and using sync for bulk creation/deletion of users, is it possible to bulk update display names using the exported ts_auth_sync_users.csv file as source?

I've tried using sync to change a display name for 1 user, but the change didn't reflect in ThoughtSpot.

**Comment by boonhapus** [comment]
Hey @aldrichsison ,

This should be possible today. There's a flag on the `user-management sync` command that says `--apply-changes` , by default it is set to false.

![image](https://user-images.githubusercontent.com/14192437/216510104-341f6399-7dbc-4e3d-b4e9-733401a6a560.png)

With this tool, we are primarily wrapping the [`user/sync` REST API](https://developers.thoughtspot.com/docs/?pageid=user-api#user-sync) if you want to read a bit more about it.

**Comment by aldrichsison** [comment]
Hi @boonhapus ,
Using `--apply-changes` worked.
I previously omitted that thinking there's an implicit commit for the change.

Thank you so much.
