### ISSUE TITLE
Additional ts_user data for Searchable and User Management

### ISSUE THREAD

**Issue by aldrichsison** [thoughtspot/cs_tools#45]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Hi!
Considering the current ERD / data model for ThoughtSpot metadata that can be extracted using Searchable,
is it possible to add more fields related to ts_user table?

For our use case, we're looking at using Searchable to extract user preferences like preferred locale & current answer or liveboard experience. Furthermore, for User Management, given the additional fields if provided, we're looking at managing preferences in bulk.

Thank you.

**Comment by boonhapus** [comment]
Hey @aldrichsison !

This is an interesting one. I'm planning on expanding the Searchable data model in one of the 1.4.x releases, but I haven't decided on what additional attributes I want to add.

It looks like we don't store this information in a public API at the moment. 

We're currently pulling this information from the `GET user/` API. The usual way to get around this kind of limitation in public api support would be to hit the `GET metadata/details` endpoint and filter down that response to that interesting information, but even this won't show that information at this time.

I'll make an ask internally to see how we can expose this information in a V2.0 REST API endpoint, but at this time we won't be able to include it in the Searchable data model.

**Comment by aldrichsison** [comment]
Hi @boonhapus ,

Thank you for providing info and making an internal inquiry regarding this question.
We'll keep an eye out future releases for cs_tools and REST APIs.

We would really appreciate if ThoughtSpot can consider adding these capabilities in the near future.
This is so we can improve on administration and user management for TS.

Cheers!

**Comment by boonhapus** [comment]
@aldrichsison absolutely!

A great way to post this feedback officially to ThoughtSpot is in our community forum, there's a [Product Ideas](https://community.thoughtspot.com/customers/s/article/How-to-suggest-a-great-Product-Idea) section where you can request new features. Other customers can see those ideas and vote weight them up as well.
