### ISSUE TITLE
Changing ownership / author for Pinned Answers

### ISSUE THREAD

**Issue by aldrichsison** [thoughtspot/cs_tools#46]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

Hi!
We're using `user-management transfer` for transferring ownership / authorship for Liveboards and Saved Answers.
However, for Pinned Answers (unsaved and directly pinned Answers to Liveboards), given that they don't have their own object IDs, is it possible reassign the ownership using cs_tools, or via API?

Thank you.

**Comment by boonhapus** [comment]
Can you help me understand what you mean here? You're unable to share an individual visualization on a Liveboard. Attempting to do so on the Classic Liveboard experience requires you to share the entire Liveboard.

![image](https://user-images.githubusercontent.com/14192437/218282919-b02156b9-90aa-44fb-ab08-d788b8479e64.png)

**Comment by aldrichsison** [comment]
Hi @boonhapus ,

This is for transferring object ownership, which we can do via API (screenshot) or via cs_tools `user-management transfer`:
<img width="579" alt="transfer_ownership" src="https://user-images.githubusercontent.com/74671574/218383101-2ec5af06-0bd9-4850-8262-109f37c50cb7.PNG">

We want to be able to transfer ownership for pinned answers within a liveboard, so when users try to search for answers/liveboards in Home page, they will no longer see the original owner/author of the answer.
For example, _Aldrich - sample kpi_ is pinned in _Aldrich - sample kpi liveboard_. We can easily change the owner for the liveboard, but for _Aldrich - sample kpi_, we can't seem to do so because it doesn't have its own object ID.
<img width="424" alt="sample_kpi" src="https://user-images.githubusercontent.com/74671574/218384039-1bb19550-b63a-4fc4-9234-b5c888fadfa6.PNG">

**Comment by boonhapus** [comment]
I see. You would need to transfer the owner of the Liveboard to the appropriate person. That *should* update all visualization owners in the homepage Search within 24hrs as well.

If it doesn't, I would consider this a bug in ThoughtSpot.

**Comment by boonhapus** [comment]
Closing as this is not a feature that ThoughtSpot supports.
