### ISSUE TITLE
Error 500 for user-management sync

### ISSUE THREAD

**Issue by aldrichsison** [thoughtspot/cs_tools#47]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

PS C:\Users\aldri> cs_tools platform --config prod

        [PLATFORM DETAILS]
        system: Windows (detail: Windows-10-10.0.22621-SP0)
        python: 3.10.7
        ran at: Friday, February 10th 2023 @ 17:20:41 PM (+08)
        cs_tools: v1.3.4

        [THOUGHTSPOT]
        cluster id: b6684241-0489-11ed-9424-c3223
        cluster: cwt
        url: https://cwt.thoughtspot.cloud/
        timezone: UTC
        branch: cloud
        version: 8.10.0.cl-133

        [LOGGED IN USER]
        user_id: 73cf1217-4f5b-41b7-8bea-8bec2e606156
        username: U384AXS@mycwt.com
        display_name: Sison, Aldrich Paul
        privileges: ['can_administer_thoughtspot', 'innate', 'can_upload_user_data', 'can_download_data', 'can_manage_data',
'can_share_with_all_users', 'has_spotiq_privilege', 'can_administer_and_bypass_rls']

PS C:\Users\aldri> cs_tools platform --config non-prod

        [PLATFORM DETAILS]
        system: Windows (detail: Windows-10-10.0.22621-SP0)
        python: 3.10.7
        ran at: Friday, February 10th 2023 @ 17:21:16 PM (+08)
        cs_tools: v1.3.4

        [THOUGHTSPOT]
        cluster id: 8092431a-73fa-11ec-b975-43cc9
        cluster: cwt-dev
        url: https://cwt-dev.thoughtspot.cloud/
        timezone: UTC
        branch: cloud
        version: 8.10.0.cl-133

        [LOGGED IN USER]
        user_id: 73cf1217-4f5b-41b7-8bea-8bec2e606156
        username: U384AXS@mycwt.com
        display_name: Sison, Aldrich Paul
        privileges: ['can_administer_thoughtspot', 'innate', 'can_upload_user_data', 'can_download_data', 'can_manage_data',
'can_share_with_all_users', 'has_spotiq_privilege', 'can_administer_and_bypass_rls']

### Example Command

- cs_tools tools user-management sync --config prod --dont-remove-deleted --apply-changes csv://C:\work\thoughtspot\cs_tools_dump\_csv-definition.toml

- cs_tools tools user-management sync --config non-prod --dont-remove-deleted --apply-changes csv://C:\work\thoughtspot\cs_tools_dump\_csv-definition.toml

### Description

Hello.
Encountering Error 500 when trying to use `user-management sync` separately on our Cloud prod and nonprod.
We can perform `export` and `searchable gather`, but `sync` from ts_auth_sync_users.csv to update user details is returning Error 500.
We managed to make this work before, so we're lost as to what could cause this error.

Attached .txt file of error message from cs_tools:
[cs_tools_error500.txt](https://github.com/thoughtspot/cs_tools/files/10705848/cs_tools_error500.txt)

**Comment by boonhapus** [comment]
I'm not able to reproduce this in my own 8.10.0 environment. Can you re-run with the `--verbose` flag and then share your log?

```
cs_tools logs export --latest 1 .
```

**Comment by aldrichsison** [comment]
Hi @boonhapus ,

Please see attachment for error log file.
[2023-02-13T14_31_48.log](https://github.com/thoughtspot/cs_tools/files/10719458/2023-02-13T14_31_48.log)

Thank you.

**Comment by boonhapus** [comment]
Thanks @aldrichsison ! It looks like this might be due to how ThoughtSpot handles the form data between versions. In the latest version, it now expects `multipart/form-data` whereas before `application/x-www-form-urlencoded` and `application/json` were both perfectly acceptable.

This is working in the latest CS Tools 1.4.0 beta, but this would replace your existing environment. If you'd like, I can share instructions on how to grab the new beta version and you can test out `user-management sync` again?

**Comment by aldrichsison** [comment]
Hi @boonhapus,
Yes, would be happy to test out 1.4.0 Beta.

Thank you.
