### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Eocin1** [thoughtspot/cs_tools#50]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

I am new to CS Tool 
While Installation CS tool I am having trouble
Windows 11
Python --version: Python 3.11.2
PS C:\Users\Pxxxxxx\Downloads\cs_tools-bootstrapper> python bootstrap --reinstall
python : 12:53:42 [0;37m| Welcome to the CS Tools Installation script![0m
At line:1 char:1
+ python bootstrap --reinstall
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (12:53:42 [0;37...ion script![0m:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
         [0;37m| Retrieving CS Tools metadata.[0m
         [0;37m| Installing CS Tools (1.3.4.)[0m
         [0;37m|   Creating environment.[0m
12:54:02 [0;37m|   Installing requirements via pip.[0m
12:54:05 [1;33m|   An error occurred. Removing partial environment.[0m
         [1;31m| CS Tools reinstallation failed.[0m
         [1;33m| See 'C:\Users\PXXXXXX\Downloads\cs_tools-bootstrapper\cs_tools-bootstrap-error-o3wo1bo1.log' for error logs.[0m

PS C:\Users\PXXXXXX\Downloads\cs_tools-bootstrapper> python bootstrap --install
python : 12:57:41 [0;37m| Welcome to the CS Tools Installation script![0m
At line:1 char:1
+ python bootstrap --install
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (12:57:41 [0;37...ion script![0m:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
         [0;37m| Retrieving CS Tools metadata.[0m
         [0;37m| Installing CS Tools (1.3.4.)[0m
         [0;37m|   Creating environment.[0m
12:57:59 [0;37m|   Installing requirements via pip.[0m
12:58:02 [1;33m|   An error occurred. Removing partial environment.[0m
         [1;31m| CS Tools installation failed.[0m
         [1;33m| See 'C:\Users\PXXXXXX\Downloads\cs_tools-bootstrapper\cs_tools-bootstrap-error-cwiprsa3.log' for error logs.[0m
error message in both logs is
ERROR: Could not find a version that satisfies the requirement markupsafe==2.0.1 (from versions: none)
ERROR: No matching distribution found for markupsafe==2.0.1

**Comment by boonhapus** [comment]
Hi @Eocin1 ! 

Our current release doesn't support python 3.11 yet. We'll be releasing a new version that does support it once the documentation is finalized. It's probably 1-2wks more until that time. If you'd like to try out the release candidate of v1.4.0 , you can try following the instructions below.

> Please run the below command in your terminal. It will grab the new bootstrapper and install CS Tools from the latest pre-release.
> 
> `curl -sSL https://github.com/thoughtspot/cs_tools/raw/holiday-planning/cs_tools/updater/_bootstrapper.py | python - --install --beta`
> 
> **CS Tools now requires python 3.7 or greater** to run. Additionally, we've stepped up our visual game. If you're using the built-in terminal, you might consider upgrade to one of the below options.
> 
> **macOS**
> We recommend installing a newer terminal such as [iterm2](https://iterm2.com/), [Kitty](https://sw.kovidgoyal.net/kitty/), or [WezTerm](https://wezfurlong.org/wezterm/).
> 
> **Windows**
> The new [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=en-gb&gl=GB) runs CS Tools beautifully.
