### ISSUE TITLE
Option to keep file names instead of replacing them with guids

### ISSUE THREAD

**Issue by ioanalex** [thoughtspot/cs_tools#52]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

It would be helpful to have an option to keep the TML file names as they are shown in the logs of:

```
$ cs_tools tools scriptability export tmls --tags mytag  --include-types liveboard,worksheet,view,table
[14:34:41] INFO     some_view.view.tml (Downloaded)                                                       _export.py:186
[14:34:42] INFO     some_other_view.view.tml (Downloaded)                                                 _export.py:186
           INFO     My Worksheet.worksheet.tml (Downloaded)                                               _export.py:186
[14:34:43] INFO     db_table.table.tml (Downloaded)                                                       _export.py:186
...
```

I would like to be able to keep these file names instead of the `<guid>.view|worksheet|liveboard|tabe.tml` formatted names. This would help greatly when working with the TML files in a file editor. 

The names seem to be already provided, so I guess that this can be an easy feature to add.

**Comment by boonhapus** [comment]
We considered this one when building `scriptability` and ultimately landed on `<guid>.<type>.tml` for a few reasons.

- There is no uniqueness constraint on ThoughtSpot metadata titles
- Titles may contain unsafe characters for OS filepath (`%#:$@` etc)
- (lesser concern) There is no restriction on Title length

What's your current difficulty with the guid approach, simply finding the relevant file when there's a lot of objects?

**Comment by boonhapus** [comment]
@billdback-ts and I will continue to think of creative ways to solve this problem. We totally understand the need to navigate the output data in many cases, but how we can enable that efficiently is a different problem.

The GUID mapping file that's exported should help give you guid traversal properties.. maybe we can augment that with the name of the object as well, as that _should be_ identical in most cases.

I'll close this now as it's not strictly planned, but will absolutely continue to monitor feedback in this area.
