### ISSUE TITLE
How to I create the mappings file for v1.4.0

### ISSUE THREAD

**Issue by ioanalex** [thoughtspot/cs_tools#53]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my account team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Description

In the docs I see that there is a migrate scenario under `scriptability` which is important to transfer to v1.4. Quoting the docs:

> 2. Create a mapping file for tables if one doesn't exist. Note that you can use scriptability create-mapping to create a new, empty mapping file.

When I try this command I get:

```
$ cs_tools tools scriptability create-mapping 
[15:49:46] ERROR    No such command 'create-mapping'.                main.py:135
```

Can you explain how this `migrate` scenario will work in v1.4? 

FYI
```
cs_tools self info
╭─────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                     │
│               CS Tools: 1.4.0rc4                                                                    │
│         Python Version: Python 3.9.13 (main, Nov  9 2022, 13:16:24)                                 │
│    [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]                                                          │
│            System Info: Linux (detail: Linux-4.18.0-425.10.1.el8_7.x86_64-x86_64-with-glibc2.28)    │
│      Configs Directory: /home/aioannou/.config/cs_tools                                             │
│    Activate VirtualEnv: source /home/aioannou/.config/cs_tools/.cs_tools/bin/activate               │
│          Platform Tags: linux-x86_64                                                                │
│                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by billdback-ts** [comment]
@ioanalex The docs are for the previous version and are being updated.  The create-mapping  command no longer exists.  A mapping file will be created the first time you run and use the map file flag.  Also, note that the format for the mapping file has changed significantly, so the old format is no longer valid.

**Comment by ioanalex** [comment]
Hi @billdback-ts, thanks for clarifying. I executed something like  

```
cs_tools tools scriptability import tmls --import-policy ALL_OR_NONE --tags clitest --tml-logs tml-logs --guid-file guid.mappings --from-env dev --to-env clitest
```

and I saw that the `guid.mappings` file was indeed created. 

I wanted to ask if we can use a syncer to fetch this mapping file from something like an S3 bucket.

**Comment by billdback-ts** [comment]
@ioanalex no currently, but that's a good idea.

**Comment by ioanalex** [comment]
Alright, one more question. When migrating TMLs we also need to change the `db`, `schema` and `connection` fields as well. Is there any support for this, or should we script around it?

**Comment by boonhapus** [comment]
Ah @ioanalex , is it because each fully qualified path corresponds to a different data quality environment? 

We've gone back and forth on where these sort of "offline" TML management workflows should live. This might be something better suited for our upstream [`thoughtspot_tml`](https://github.com/thoughtspot/thoughtspot_tml/tree/v2_0_release/examples) library as a code example + short .py script.

**Comment by boonhapus** [comment]
Also for the "fetch from/dump to S3 bucket" -- totally hear you.

Right now, the workaround is to mount the S3 bucket to your local filesystem. I've used **[PyFilesystem](https://docs.pyfilesystem.org/en/latest/guide.html#why-use-pyfilesystem)** for this abstraction in the past and wouldn't be opposed to integrating it here.

Then you could effectively set your output directory there with something like..

```
cs_tools tools scriptability import `
s3://<aws.access_key>:<aws.secret_key>@<directory>
--import-policy ALL_OR_NONE `
--tags clitest `
--tml-logs tml-logs `
--guid-file guid.mappings `
--from-env dev `
--to-env clitest
```

More on the structure of the syntax **[in their documentation](https://docs.pyfilesystem.org/en/latest/openers.html)** (it might look familiar 😉). This could be fairly easy for us to support and would open the door up to writing to **[any of the fs ecosystem](https://www.pyfilesystem.org/page/index-of-filesystems/)**.
