### ISSUE TITLE
Keep getting attribute error when using searchable tool

### ISSUE THREAD

**Issue by alexwillingham98** [thoughtspot/cs_tools#59]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

Info snapshot taken on 2023-05-09                                                                        │
│                                                                                                                    │
│               CS Tools: 1.4.2                                                                                      │
│         Python Version: Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]    │
│            System Info: Windows (detail: Windows-10-10.0.19044-SP0)                                                │
│      Configs Directory: C:\Users\alexw\AppData\Roaming\cs_tools                                                    │
│    Activate VirtualEnv: C:\Users\alexw\AppData\Roaming\cs_tools\.cs_tools\Scripts\Activate.ps1                     │
│          Platform Tags: win-amd64

### Description

currently trying to run this command: 
cs_tools tools searchable gather --config TS_Prod csv://C:\Users\alexw\OneDrive\Documents\DEFINITION.toml

This command worked fine before the 1.4 update but ever since i've been getting this error: 

 C:\Users\alexw\AppData\Roaming\cs_tools\.cs_tools\lib\site-packages\cs_tools\cli\tools\searchable\app.py:270 in      
│ gather                                                                                                               
│                                                                                                                      
│   267 │                                                                                                              
│   268 │   tasks = [                                                                                                  
│   269 │   │   ("gather_groups", "Collecting [b blue]Groups [white]and[/] Privileges"),                               
│ ❱ 270 │   │   ("syncer_dump_groups", f"Writing [b blue]Groups[/] to {syncer.name}"),                                 
│   271 │   │   ("syncer_dump_group_privileges", f"Writing [b blue]Groups Privileges[/] to {sync                       
│   272 │   │   ("gather_users", "Collecting [b blue]Users"),                                                          
│   273 │   │   ("syncer_dump_users", f"Writing [b blue]Users[/] to {syncer.name}"),                                   
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'name'

I also get this error for the bi-server command as well

![image](https://github.com/thoughtspot/cs_tools/assets/88211538/c1e34caa-8a9a-40c0-b90a-0fa826b529b8)

**Comment by boonhapus** [comment]
@alexwillingham98 did you mean to close this one?

The command options changed a bit in 1.4.0 , you must use `--syncer csv://C:\Users\alexw\OneDrive\Documents\DEFINITION.toml`


![cs_tools_tools_searchable_gather___help](https://github.com/thoughtspot/cs_tools/assets/14192437/cb334abe-655d-4a36-8f00-00d0ecebe9fc)

**Comment by boonhapus** [comment]
To be fair, we can give a better error here. 😄

**Comment by alexwillingham98** [comment]
Yes, shortly after I realized the command had changed🙃 sorry about that
