### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by bmofkn** [thoughtspot/cs_tools#64]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

<img width="843" alt="Screenshot 2023-06-13 at 7 06 20 PM" src="https://github.com/thoughtspot/cs_tools/assets/119008346/c9af42ae-22ee-4bf3-820c-30b1b2ca8526">

### Description

<img width="846" alt="Screenshot 2023-06-13 at 7 07 52 PM" src="https://github.com/thoughtspot/cs_tools/assets/119008346/a5b01a0b-8547-49c1-b4b4-75e1bace64f3">

**Comment by boonhapus** [comment]
We have the `--syncer` parameter **[as optional here](https://github.com/thoughtspot/cs_tools/blob/b5533df02b2001fc54017441a172d9b40ce506e1/cs_tools/cli/tools/searchable/app.py#L152-L157)** when it should be required.

@bmofkn to get past this one, please use `--syncer` with one of the supported protocols.

**Comment by boonhapus** [comment]
@bmofkn Thanks for reporting this one! I have updated the `--syncer` option to be required as part of 1.4.8 , you can take the update with `cs_tools self update`.
