### ISSUE TITLE
cstools config show should list results sorted

### ISSUE THREAD

**Issue by billdback-ts** [thoughtspot/cs_tools#66]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

![image](https://github.com/thoughtspot/cs_tools/assets/32280587/b00fd602-96b6-4440-bd7a-5a362b774035)

### Description

cstools config show gives a list of configs that have been created.  But they are out of order.  It would be nice to have the list sorted for scenarios with a long list of configs.

**Comment by suresh900** [comment]
Hi Can any one help us on this command, what happened when we run this command -  
cs_tools tools user-management sync --syncer csv://directory=C:\Users --config PROD1234 --apply-changes

**Comment by boonhapus** [comment]
@suresh900 let's continue on 👉 **[this thread](https://github.com/thoughtspot/cs_tools/issues/68)** -- please share a screenshot of your error , or use `cs_tools logs report` and add the file into the issue comment field.

**Comment by suresh900** [comment]
<Response [201 Created]>

**Comment by boonhapus** [comment]
Implemented in **[v1.4.13](https://github.com/thoughtspot/cs_tools/commit/372b0c4f1ab510b7437984592c59f8414209730f)**
