### ISSUE TITLE
Import of freshly exported connection.tml file fails

### ISSUE THREAD

**Issue by Mika45** [thoughtspot/cs_tools#72]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

![cs-tools-info-2023-10-11](https://github.com/thoughtspot/cs_tools/assets/3518011/807f0ab6-ec50-449e-85aa-2c0469f1e6e7)

### Description

I have exported a connection using "cs_tools scriptability export" successfully and that produced a .connection.tml file that I'm trying to import directly back to the same Org for test purposes (before I update any attributes in it). So, after having manually typed the db password (connection is of type "RDBMS_ORACLE_ADW") I run the appropriate "cs_tools scriptability import" command and that produces a python KeyError. Please see details in the log file attached.
[2023-10-11T07_42_54.log](https://github.com/thoughtspot/cs_tools/files/12865847/2023-10-11T07_42_54.log)

**Comment by boonhapus** [comment]
@Mika45 I just pushed v1.4.11 , you should be able to take it with `cs_tools self upgrade` . Let me know if that fixes your error!

---

❗ It's possible that you might run into an issue with `cs_tools self upgrade` as I had a bug in the installer itself. If your upgrade command fails, please go to `/Users/mtsilikidis/Library/Application Support/cs_tools/.cs_tools` (the directory with the dot in front of it) and remove it all (`cd /Users/mtsilikidis/Library/Application Support/cs_tools/.cs_tools && rm -rf`), **[then try installing again](https://thoughtspot.github.io/cs_tools/changelog/1.4.0/)**.

**Comment by boonhapus** [comment]
Closing this one out -- if it's still not working, feel free to open it back up!
