### ISSUE TITLE
Cannot export connection using the scriptability export tool

### ISSUE THREAD

**Issue by Mika45** [thoughtspot/cs_tools#74]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

![cs-tools-info-2023-10-16](https://github.com/thoughtspot/cs_tools/assets/3518011/7c7412f3-1a24-4a1e-b8bd-3c175be8610c)

### Description

Simple export command with cs_tools is not able to export the connection tml file anymore while this was working okay 2 days ago. The command I'm passing:
`cs_tools tools scriptability export ./export/ --pattern ORA_VPN --include-types connection --org RAMBO --config dev-cfg`

Attaching the result of the logs report command.
[2023-10-16T14_36_59.log](https://github.com/thoughtspot/cs_tools/files/12917231/2023-10-16T14_36_59.log)

**Comment by billdback-ts** [comment]
@Mika45 Sorry about the problem there.  There was an issue with the calls to the API.  I've checked in a version and hopefully we can get that merged in and released ASAP.

**Comment by boonhapus** [comment]
This should be fixed now -- 1.4.12 is available to install, **[like we did before](https://github.com/thoughtspot/cs_tools/issues/72#issuecomment-1763576261)**.

**Comment by boonhapus** [comment]
Closing this one out -- if it's still not working, feel free to open it back up!
