### ISSUE TITLE
User management sync not working for windows

### ISSUE THREAD

**Issue by sae-bruce** [thoughtspot/cs_tools#80]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

(base) PS C:\Downloads> cs_tools self info --anonymous --directory ..
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                    │
│           Info snapshot taken on 2023-11-10                                                                                        │
│                                                                                                                                    │
│               CS Tools: 1.4.13                                                                                                     │
│         Python Version: Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]    │
│            System Info: Windows (detail: Windows-10-10.0.19044-SP0)                                                                │
│      Configs Directory: C:\Users\m172485\AppData\Roaming\cs_tools                                                                  │
│    Activate VirtualEnv: C:\Users\m172485\AppData\Roaming\cs_tools\.cs_tools\Scripts\Activate.ps1                                   │
│          Platform Tags: win-amd64                                                                                                  │
│                                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(base) PS C:\Downloads>

[logs_report.txt](https://github.com/thoughtspot/cs_tools/files/13316477/logs_report.txt)
[windows_output.txt](https://github.com/thoughtspot/cs_tools/files/13316479/windows_output.txt)

### Description

cs_tools tools user-management sync --config sae_falcon --syncer csv://user_delta.toml --export

We try to sync user from falcon instance to cloud, when we run syncer for falcon it's giving configuration error.
Error message is attached in windows_output.txt file.

**Comment by boonhapus** [comment]
For `logs_report.txt` , we can ignore this one. It gives an error trying to send analytics to our server. I'll fix this one for our next release, but it shouldn't block you from executing most code.

For the syncer issue, can you share your `user_delta.toml` file ?

**Comment by sae-bruce** [comment]
Hi @boonhapus ,

The user_delta.toml is an empty file created by us.

**Comment by boonhapus** [comment]
@sae-bruce can you make your `user_delta.toml` file looks like this?

```toml
[configuration]
directory = "."
```

The full path of where you want your CSVs to be written should be put in that argument where the period is `.`

**Comment by boonhapus** [comment]
@sae-bruce if you wanted to try this another way, you can try using this command instead.

`cs_tools tools user-management sync --config sae_falcon --syncer csv://directory="." --export`

the `"."` part is us telling CS Tools which directory to export the CSVs to. It's an alias for your operating system that means current directory. If to you supplied an absolute or full path here, it would be okay as well. Like this..

`cs_tools tools user-management sync --config sae_falcon --syncer csv://directory="C;/Downloads" --export`

Which would put the CSV files in your `Downloads` folder.
