### ISSUE TITLE
_Timezone attribute missing from new Pendulum version.

### ISSUE THREAD

**Issue by jonathandurantalkiatry** [thoughtspot/cs_tools#93]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

<img width="1013" alt="Screenshot 2023-12-18 at 11 42 04 AM" src="https://github.com/thoughtspot/cs_tools/assets/142258379/49b987f4-173e-48bf-8037-f10226ca8fae">

### Description

When attempting to set up the config file `cs_tools config create`, I am running into the error `AttributeError: module 'pendulum' has no attribute '_Timezone'`.

Looking further into this, it seems that `pendulum` had a major upgrade (`3.0.0`) and `pendulum._Timezone` is no longer available. I tested this using the previous release (`2.1.2`) and can confirm that `pendulum._Timezone` works on this version. 

I've included the traceback below.

<img width="845" alt="Screenshot 2023-12-18 at 11 46 44 AM" src="https://github.com/thoughtspot/cs_tools/assets/142258379/8614e569-f7c6-4c37-90a3-7e618f5071f6">

**Comment by boonhapus** [comment]
Hey @jonathandurantalkiatry , thanks for investigating this and finding the fix!

I'll add a restriction for `pendulum < 3.0.0` and release a `v1.4.14` to cover it.

**Comment by boonhapus** [comment]
If you re-run the install command, this should get picked up appropriately now @jonathandurantalkiatry !
