### ISSUE TITLE
INTERNAL ERROR when attempting to import liveboard (UI import works fine)

### ISSUE THREAD

**Issue by Mika45** [thoughtspot/cs_tools#98]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

![cs-tools-info-2024-01-25](https://github.com/thoughtspot/cs_tools/assets/3518011/41af03ef-9563-4991-9613-94af4fce554c)

### Description

Greetings. I'm trying to import a liveboard object via cs_tools and it fails with the error message INTERNAL ERROR which doesn't leave a clue about what could have gone wrong. Note that I've successfully managed to import the liveboard manually via the Utilities/Import TML area of TS cloud.

![image](https://github.com/thoughtspot/cs_tools/assets/3518011/8c7a2ad3-7169-477d-872f-ec916f79ae53)

Any thoughts or help on how I could debug or get a more descriptive error from cs_tools?

**Comment by boonhapus** [comment]
Hey @Mika45 , this error comes back from ThoughtSpot directly. Does this Liveboard have a parameter on it?

**Comment by Mika45** [comment]
Hi @boonhapus. No, it does not have parameters.

**Comment by boonhapus** [comment]
@Mika45 would you be able to share your TML file on **[this secure file share link](https://thoughtspot.egnyte.com/ul/exyP5qLUHK)**? I'll take a look to see if I can't find out what's going on.

**Comment by Mika45** [comment]
@boonhapus sure. I've just shared it. Thanks.

**Comment by boonhapus** [comment]
Thanks, I got it! This looks like a bug in ThoughtSpot itself, as I can see a related [internal] JIRA. I'll reach out to you directly to determine the best next steps.
